#!/usr/bin/env python3
"""
THM 24/7 Live Radio Service
Streams music continuously to YouTube Live using ffmpeg + RTMP.

Two radio channels:
  - Radio 1: Lofi/Study (for study/focus audience)
  - Radio 2: World Lounge (for world music/cultural audience)

Usage:
  python3 live_radio.py --channel lofi --stream-key <YOUTUBE_STREAM_KEY> --playlist /data/music/lofi_mixes.txt
  python3 live_radio.py --channel world --stream-key <YOUTUBE_STREAM_KEY> --playlist /data/music/world_mixes.txt
  python3 live_radio.py --channel lofi --list-key  # Just print playlist

Features:
  - Auto-restart on disconnect
  - Gapless playback (playlist-based)
  - Status endpoint via HTTP (port 8001)
  - Loop protection (never stops)
"""

import argparse
import json
import os
import subprocess
import sys
import time
import signal
from http.server import HTTPServer, BaseHTTPRequestHandler
from threading import Thread

# YouTube RTMP endpoint
RTMP_URL = "rtmp://a.rtmp.youtube.com/live2"

# Radio playlist files (generated by build pipeline)
PLAYLIST_DIR = "/data/music"

# Status state
status = {
    "channel": "",
    "streaming": False,
    "current_track": "",
    "uptime_seconds": 0,
    "restarts": 0,
    "started_at": "",
}


class StatusHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/status":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(status).encode())
        else:
            self.send_response(404)
            self.end_headers()


def load_playlist(path):
    """Load playlist file (one track path per line)."""
    if os.path.exists(path):
        with open(path) as f:
            return [line.strip() for line in f if line.strip() and os.path.exists(line.strip())]
    return []


def generate_lofi_playlist():
    """Generate lofi playlist from available mixes."""
    tracks = []
    base = "/data/music"
    candidates = [
        "lofi_mix1h.mp3", "lofi_extended.mp3",
        "ambient_mix1h.mp3", "jazz_mix1h.mp3",
    ]
    for c in candidates:
        p = os.path.join(base, c)
        if os.path.exists(p):
            tracks.append(p)
    return tracks


def generate_world_playlist():
    """Generate world music playlist from available mixes."""
    tracks = []
    base = "/data/music"
    candidates = [
        "guzheng_mix1h.mp3", "sitar_mix1h.mp3", "oud_mix1h.mp3",
        "acem_mix1h.mp3", "savanna_mix1h.mp3", "harp_mix1h.mp3",
        "viking_mix1h.mp3", "saz_mix1h.mp3",
    ]
    for c in candidates:
        p = os.path.join(base, c)
        if os.path.exists(p):
            tracks.append(p)
    return tracks


def stream_loop(playlist, stream_key):
    """Main streaming loop — restarts automatically."""
    global status
    rtmp_url = f"{RTMP_URL}/{stream_key}"
    start_time = time.time()
    status["started_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    while True:
        if not playlist:
            print("[radio] No tracks in playlist, waiting 60s...", flush=True)
            time.sleep(60)
            playlist = load_playlist(args.playlist_path) if args.playlist_path else []
            continue

        # Build ffmpeg concat command for all tracks
        filter_parts = []
        inputs = []
        for i, track in enumerate(playlist):
            inputs.extend(["-stream_loop", "-1", "-i", track])
        
        # Just use the first track, loop it, with filter for video
        track = playlist[0]
        inputs = ["-stream_loop", "-1", "-i", track, "-stream_loop", "-1", "-i", "/data/cover/radio_cover.png"]
        
        cmd = [
            "ffmpeg", "-y",
            "-re", "-stream_loop", "-1", "-i", track,
            "-loop", "1", "-framerate", "30", "-i", "/data/cover/radio_cover.png",
            "-filter_complex",
            "[0:a]volume=1.0[aout];[1:v]scale=1920:1080,format=yuv420p[vout]",
            "-map", "[vout]", "-map", "[aout]",
            "-c:v", "libx264", "-preset", "veryfast", "-b:v", "4500k",
            "-maxrate", "6000k", "-bufsize", "12000k",
            "-g", "60", "-keyint_min", "60",
            "-c:a", "aac", "-b:a", "128k", "-ar", "44100", "-ac", "2",
            "-f", "flv", rtmp_url
        ]
        
        print(f"[radio] Starting stream with: {os.path.basename(track)}", flush=True)
        status["current_track"] = os.path.basename(track)
        status["streaming"] = True
        
        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                preexec_fn=os.setsid
            )
            proc.wait()
        except Exception as e:
            print(f"[radio] Stream error: {e}", flush=True)
        
        status["streaming"] = False
        status["restarts"] += 1
        print(f"[radio] Stream ended (restart #{status['restarts']}), retrying in 10s...", flush=True)
        time.sleep(10)


def main():
    global args
    parser = argparse.ArgumentParser(description="THM 24/7 Live Radio")
    parser.add_argument("--channel", choices=["lofi", "world"], required=True)
    parser.add_argument("--stream-key", required=True)
    parser.add_argument("--playlist", help="Custom playlist file path")
    parser.add_argument("--port", type=int, default=8001)
    args = parser.parse_args()

    status["channel"] = args.channel

    # Start status HTTP server
    def run_status_server():
        server = HTTPServer(("0.0.0.0", args.port), StatusHandler)
        server.serve_forever()
    
    Thread(target=run_status_server, daemon=True).start()
    print(f"[radio] Status server on port {args.port}", flush=True)

    # Load or generate playlist
    if args.playlist:
        playlist = load_playlist(args.playlist)
    elif args.channel == "lofi":
        playlist = generate_lofi_playlist()
    else:
        playlist = generate_world_playlist()

    if not playlist:
        print(f"[radio] WARNING: No tracks found for {args.channel}", flush=True)
        print("[radio] Waiting for music files to be available...", flush=True)

    print(f"[radio] {args.channel} radio starting with {len(playlist)} tracks", flush=True)
    stream_loop(playlist, args.stream_key)


if __name__ == "__main__":
    main()
